#!/bin/sh

# disable file extension rename warning
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# show file extensions in finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# column view by default in finder
defaults write com.apple.finder FXPreferredViewStyle Clmv

# dock on left
defaults write com.apple.dock 'orientation' -string 'left'

# smaller dock icons
defaults write com.apple.dock tilesize -int 34

# pink highlight color
defaults write NSGlobalDomain AppleHighlightColor -string "1.000000 0.749020 0.823529 Pink"

# put screenshots in ~/Desktop/screenshots
mkdir -p ~/Desktop/screenshots
defaults write com.apple.screencapture location ~/Desktop/screenshots

# turn off the hold-to-show-accents thing
defaults write -g ApplePressAndHoldEnabled -bool false

# faster repeat + shorter delay on key hold
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 2

# turn off .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# password after screensaver
defaults write com.apple.screensaver askForPassword -bool true
defaults write com.apple.screensaver askForPasswordDelay -int 0
