let mapleader = '\'

" set colorcolumn=80 " let &colorcolumn=80
map Y y$             " Make Y match C/D/&c behavior, i.e., yank to end of line
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
set showmatch
filetype plugin indent on
syntax on
set undofile
set backupdir=~/.vim/backup/
set directory=~/.vim/swap/
set undodir=~/.vim/undo/
" set foldmethod=marker

set background=light
colorscheme default
set number ruler
set cursorline
set scrolloff=6

" if you're ever stuck in cmder or something else with (I guess?) non-ANSI
" terminal color compatibility or whatever
highlight Visual cterm=bold ctermbg=Blue ctermfg=NONE

set display+=lastline " Prevent showing @ signs when a really long line doesn't fit entirely on the screen
set noshowmode        " Hide the default mode text that's usually below the powerline
set showtabline=2     " Always show tabs, even if only one is open
set backspace=2       " Make backspace work as you're trained to expect in insert mode

highlight Search ctermbg=220
set incsearch hlsearch
map <Leader>h :noh<CR>
set ignorecase smartcase " only do case-sensitive if you type caps

" Move by visual line instead of actual line; when a line wraps around, j will
" now move down to the wrapped text instead of skipping over it
nnoremap j gj
nnoremap k gk
" Snap line under cursor to middle of screen
nnoremap <Space> zz

nnoremap - ddkP
nnoremap + ddp

" Remove all trailing whitespace
map <Leader>$ :%s/\s\+$//g<CR>
" and any trailing lines that are either empty or contain only whitespace
" second one important bits are:
" $ is just end of a line, not newline, so you need a \n or it'll only match
" the last line of the file
" but the last line doesn't have a newline so you need a ? too
" %$ is end of file
map <Leader>% :g/\v(^\s*$\n?)+%$/d<CR>

" more intuitive splitting behavior
set splitbelow splitright

" ------ Buffers ------
nnoremap <C-q> :bprevious<CR>
nnoremap <C-e> :bnext<CR>
nnoremap <C-t> :enew<CR>
nnoremap <C-d> :bprevious\|bdelete #<CR>

" Keep unfocused buffers loaded
set hidden
